name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyrefly argcomplete
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: ruff
      uses: astral-sh/ruff-action@v3
      with:
        version: latest
    - name: pyrefly
      run: |
        pyrefly check

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: build and inspect
      uses: hynek/build-and-inspect-python-package@v2
